### ISSUE TITLE
PA Review: Frontend Routes

### ISSUE THREAD

**Issue by Shhmabbey** [iamxiwang/greenfin#6]
# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by Shhmabbey** [comment]
Looks correct but you'll want to add appointments. I've included another sample so that you can look at a different way to format your routes

**Comment by Shhmabbey** [comment]
## Frontend Routes
* `/`
  * `Homepage`
    * `NavigationBar`
* `/users`
    * `UserForms`
      * `LoginForm`
      * `SignUpForm`
* `/carts/:id`
  * `CartIndex`
    * `CartIndexItem`
* `/products`
  * `ProductsIndex`
    * `ProductsIndexItem`
* `/products/:id`
  * `ProductsShow`
    * `ProductsShowItem`
      * `ReviewsIndex`
      * `ReviewForm`

**Comment by iamxiwang** [comment]
- change table appointments to tours, then add  `/tours`, `/tours/:id`, `/tours/:id/edit` .
- add listings index and show routes
- add add agent show routes
